version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./dist:/var/www
    ports:
      - 5173:85
    networks:
      - web

networks:
  web:

