version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./dist:/var/www
    ports:
      - 8086:80
    networks:
      - web
  api:
    build:
      context: src/shared/api/mock
      dockerfile: DockerFile
    restart: always
    volumes:
      - ./dist:/var/www
    ports:
      - 3000:3000
    networks:
      - web
networks:
  web:

